// bun run package -- <post-key> [--help]
//
// Pipeline step: write caption.txt, alt_text.txt, sources.md, LICENSES.md, QA checklist
// into pipeline/renders/<folder>/ (alongside export PNGs). Does not render slides.
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import {
  captionTxt,
  slideCaptionsOutputName,
  slideCaptionsTxt,
} from "../src/lib/caption-export.ts";
import type { TPostData } from "../src/lib/schema.ts";
import { multipleCaptionsEnabled } from "../src/lib/schema.ts";
import { instagramUploadChecklist } from "./lib/instagram-upload.ts";
import { loadPost, outputDir, slideFilename } from "./lib.ts";

function altTextTxt(post: TPostData): string {
  // One paste-ready alt-text block per slide, in slide order, separated by a blank line — no
  // "NN."/"Slide N" label prefixes (those would be read aloud by a screen reader). The uploader
  // copies each block into that slide's Instagram alt-text field.
  return post.alt_text.map((a) => a.trim()).join("\n\n") + "\n";
}

function sourcesMd(post: TPostData): string {
  const lines = [
    `# Sources — ${post.post_id}`,
    "",
    `**Core claim:** ${post.core_claim}`,
    `**Claim tags:** ${post.claim_tags.join(", ")}`,
    "",
    "| Source | Link | Supports | Confidence | Claim tag |",
    "| --- | --- | --- | --- | --- |",
    ...post.sources.map(
      (s) =>
        `| ${s.source} | ${s.link} | ${s.supports} | ${s.confidence} | ${s.claim_tag} |`,
    ),
    "",
    "> Re-open every link before posting and confirm the claim still matches the source wording.",
    "",
  ];
  return lines.join("\n");
}

function audioLines(post: TPostData): string[] {
  if (!post.video?.enabled) return ["No Reel in this package."];
  const a = (
    post.video as { audio?: { voice_mode?: string; music_mode?: string } }
  ).audio;
  const voice = a?.voice_mode ?? "none";
  const music = a?.music_mode ?? "none";
  if (voice === "none" && music === "none") {
    return [
      "This Reel renders **without audio** (voice_mode/music_mode = none). To narrate it, set the modes and add the files — see REMOTION_REEL_WORKFLOW.md → Audio.",
    ];
  }
  const out = [
    "| Asset | Mode | Source / license | Commercial use | Disclosure |",
    "| --- | --- | --- | --- | --- |",
  ];
  if (voice !== "none")
    out.push(
      `| voice.wav | ${voice} | ${voice === "voxcpm2" ? "VoxCPM2 (Apache-2.0)" : "TODO — fill in"} | ${voice === "voxcpm2" ? "yes" : "TODO"} | ${voice === "voxcpm2" ? "AI-audio label required" : "TODO"} |`,
    );
  if (music !== "none")
    out.push(
      `| music.mp3 | ${music} | TODO — name the track + license URL | TODO | TODO |`,
    );
  out.push(
    "",
    "> Fill every TODO before publishing (QA Gate 7). Do NOT use F5-TTS base weights (CC-BY-NC).",
  );
  return out;
}

function licensesMd(post: TPostData): string {
  const assetLines = (
    post.asset_licenses as Array<Record<string, unknown>>
  ).map(
    (a) =>
      `| ${a.asset ?? ""} | ${a.source ?? ""} | ${a.license_or_terms ?? ""} | ${a.commercial_use_allowed ? "yes" : "no"} | ${a.disclosure_required ? "yes" : "no"} |`,
  );
  return [
    `# LICENSES — ${post.post_id}`,
    "",
    "Tracks rights for every asset that appears in the rendered package (QA Gate 7).",
    "",
    "## Image / background assets",
    "| Asset | Source | License / terms | Commercial use | Disclosure |",
    "| --- | --- | --- | --- | --- |",
    ...(assetLines.length ? assetLines : ["| (none) | — | — | — | — |"]),
    "",
    "## Audio / video (Reel)",
    ...audioLines(post),
    "",
  ].join("\n");
}

function qaChecklistMd(post: TPostData): string {
  const files = post.slides.map((_, i) => slideFilename(post, i));
  return [
    `# Render QA Checklist — ${post.post_id}`,
    "",
    `Generated by the renderer. Cross-reference ../../pipeline/content/QA_CHECKLIST.md (content gates) — this file covers render-specific gates.`,
    "",
    "| Gate | Check | Result |",
    "| --- | --- | --- |",
    `| Resolution | All slides exactly ${post.canvas.width}×${post.canvas.height} | auto-verified by export-carousel (fails build if wrong) |`,
    `| Ordering | Filenames sort 01→${String(post.slides.length).padStart(2, "0")} | PASS (role-based naming) |`,
    `| Alt text | Count matches slides (${post.alt_text.length}/${post.slides.length}) | ${post.alt_text.length === post.slides.length ? "PASS" : "FAIL"} |`,
    `| Source support | ≥1 sourced/qualified claim | ${post.sources.length >= 1 ? "PASS" : "FAIL"} (${post.sources.length} sources) |`,
    `| Cyber safety | No payloads/exploit/evasion in copy | MANUAL REVIEW — confirm |`,
    `| Defender value | Defense + takeaway slides present | ${post.slides.some((s) => s.role === "defense") ? "PASS" : "FAIL"} |`,
    `| Text overflow | No clipped headline / hidden CTA in exported PNGs | MANUAL REVIEW — eyeball cover + slide 6 |`,
    `| Mobile readability | Cover legible as a thumbnail | MANUAL REVIEW |`,
    `| Brand consistency | Accent (${post.brand.pillar_accent}), handle, pagination consistent | PASS (shared shell) |`,
    `| Media rights | Asset/audio licenses logged | ${post.asset_licenses.length ? "PASS" : "REVIEW"} (see LICENSES.md) |`,
    `| Upload readiness | caption/alt/sources present | PASS |`,
    multipleCaptionsEnabled(post)
      ? `| Per-slide IG captions | multiple_captions on; slide_captions count | ${post.slide_captions?.length === post.slides.length ? "PASS" : "FAIL"} (${post.slide_captions?.length ?? 0}/${post.slides.length}) |`
      : "",
    "",
    "## Files in this package",
    ...files.map((f) => `- ${f}`),
    post.video?.enabled ? `- ${post.video.export_name} (Reel)` : "",
    "- caption.txt",
    ...(multipleCaptionsEnabled(post)
      ? [`- ${slideCaptionsOutputName(post)}`]
      : []),
    "- instagram_upload_checklist.md",
    "- alt_text.txt",
    "- sources.md",
    "- LICENSES.md",
    "- render_qa_checklist.md",
    "",
    "> Manual-review rows must be eyeballed before posting. The renderer enforces the mechanical gates; a human still owns the credibility + safety call.",
    "",
  ]
    .filter(Boolean)
    .join("\n");
}

function main() {
  const args = process.argv.slice(2);
  if (args.includes("--help") || args.includes("-h")) {
    console.log(`
bun run package — upload metadata files for a post

USAGE
  bun run package -- <post-key>

OUTPUT (under pipeline/renders/<folder>/)
  caption.txt, alt_text.txt, sources.md, LICENSES.md, render_qa_checklist.md
  (+ slide_captions.txt + instagram_upload_checklist.md when features.multiple_captions is on)

EXAMPLES
  bun run package -- my-post
`);
    process.exit(0);
  }
  const key =
    args.find((a) => !a.startsWith("--")) ?? "2026-06-02_ai-phishing-training";
  const post = loadPost(key);
  const outDir = outputDir(post);
  mkdirSync(outDir, { recursive: true });

  const writes: Array<[string, string]> = [
    [post.upload_package.caption_file ?? "caption.txt", captionTxt(post)],
    ["alt_text.txt", altTextTxt(post)],
    ["sources.md", sourcesMd(post)],
    ["LICENSES.md", licensesMd(post)],
    ["render_qa_checklist.md", qaChecklistMd(post)],
    ["instagram_upload_checklist.md", instagramUploadChecklist(post, outDir)],
  ];
  const slideCaptions = slideCaptionsTxt(post);
  if (slideCaptions !== null) {
    writes.push([slideCaptionsOutputName(post), slideCaptions]);
  }
  for (const [name, content] of writes) {
    writeFileSync(path.join(outDir, name), content, "utf8");
    console.log(`  ✓ ${name}`);
  }

  // Warn if slide PNGs are not present yet (run `bun run export` first).
  const firstPng = slideFilename(post, 0);
  if (!existsSync(path.join(outDir, firstPng))) {
    console.warn(
      `\n⚠ Slide PNGs not found in ${outDir}. Run: bun run export -- ${key}`,
    );
  }
  console.log(`\n✓ Package metadata written to ${outDir}`);
}

main();
